# Generated by Django 3.2.4 on 2021-06-21 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.login'),
        ),
        migrations.AlterField(
            model_name='createuser',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.address'),
        ),
        migrations.AlterField(
            model_name='createuser',
            name='initial_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.login'),
        ),
    ]
